# Конфигурация TrafficMask сервера

server:
  host: "0.0.0.0"
  port: 8080

security:
  enable_signature_masking: true
  allowed_signatures:
    - "http_header_masker"
    - "tls_fingerprint_masker"
    - "dns_query_masker"
    - "sni_masker"
    - "ip_sidr_masker"
    - "vk_tunnel_masker"
    - "encrypted_traffic_masker"
    - "vless_masker"
  blocked_patterns:
    - "malicious_pattern_1"
    - "malicious_pattern_2"

logging:
  level: "info"
  format: "text"

# Настройки C++ ядра
cpp_core:
  max_connections: 1000
  buffer_size: 8192
  worker_threads: 4
  
# Настройки сигнатур
signatures:
  http_headers:
    enabled: true
    mask_user_agent: true
    mask_accept_headers: true
    
  tls_fingerprint:
    enabled: true
    mask_cipher_suites: true
    mask_extensions: true
    
  dns_queries:
    enabled: true
    mask_query_id: true
    mask_domain_names: false
    
  sni_masking:
    enabled: true
    mask_domains:
      - "vk.com"
      - "vk.ru"
      - "mail.ru"
      - "yandex.ru"
      - "rambler.ru"
      - "ok.ru"
      - "rutracker.org"
      - "1c.ru"
      - "gismeteo.ru"
      - "kinopoisk.ru"
      - "avito.ru"
      - "aliexpress.ru"
      - "wildberries.ru"
      - "ozon.ru"
      - "dns-shop.ru"
    randomize_selection: true
    
  ip_sidr:
    enabled: true
    mask_source_ip: true
    mask_pool:
      - "77.88.8.8"      # Yandex DNS
      - "77.88.8.9"      # Yandex DNS
      - "77.88.8.10"     # Yandex DNS
      - "77.88.8.11"     # Yandex DNS
      - "77.88.quit.55"   # Yandex
      - "77.88.quit.56"   # Yandex
      - "77.88.quit.57"   # Yandex
      - "77.88.quit.58"   # Yandex
      - "13.13.13.13"    # Mail.ru
      - "13.13.13.14"    # Mail.ru
      - "13.13.13.15"    # Mail.ru
      - "13.13.13.16"    # Mail.ru
      - "46.46.46.46"    # Rambler
      - "46.46.46.47"    # Rambler
      - "46.46.46.48"    # Rambler
      - "46.46.46.49"    # Rambler
      - "31.31.31.31"    # VK
      - "31.31.31.32"    # VK
      - "31.31.31.33"    # VK
      - "31.31.31.34"    # VK
      - "87.250.250.242" # Yandex
      - "87.250.250.243" # Yandex
      - "87.250.250.244" # Yandex
      - "87.250.250.245" # Yandex
    consistent_mapping: true
    
  vk_tunnel:
    enabled: true
    replace_vk_apps: true
    replacement_domains:
      - "vk.com"
      - "mail.ru"
      - "yandex.ru"
      - "ok.ru"
      - "rutracker.org"
    cdn_support: true
    websocket_support: true
    
  encrypted_traffic:
    enabled: true
    tcp_support: true
    udp_support: true
    tls_versions:
      - "1.0"
      - "1.1"
      - "1.2"
      - "1.3"
    mask_payload: true
    preserve_headers: true
    
  whitelist_database:
    enabled: true
    auto_scan: true
    scan_intervals: 300  # секунды
    russia_domains_only: true
    allowed_ranges:
      - "77.88.8.0/24"    # Yandex DNS
      - "13.13.13.0/24"    # Mail.ru
      - "46.46.46.0/24"    # Rambler
      - "31.31.31.0/24"    # VK
      - "87.250.250.240/28" # Yandex CDN
    
  vless_protocol:
    enabled: true
    support_reality: true
    support_vision: true
    support_xtls: true
    russia_uuids:
      - "550e8400-e29b-41d4-a716-446655440001"  # Яндекс
      - "550e8400-e29b-41d4-a716-446655440002"  # Mail.ru
      - "550e8400-e29b-41d4-a716-446655440003"  # Rambler
      - "550e8400-e29b-41d4-a716-446655440004"  # VK
      - "550e8400-e29b-41d4-a716-446655440005"  # OK
      - "550e8400-e29b-41d4-a716-446655440006"  # Rutracker
      - "550e8400-e29b-41d4-a716-446655440007"  # 1C
      - "550e8400-e29b-41d4-a716-446655440008"  # Gismeteo
    mask_uuid: true
    mask_commands: true
    force_tcp: true
    
  vk_tunnel:
    enabled: true
    replace_vk_apps: true
    replacement_domains:
      - "vk.com"
      - "mail.ru"
      - "yandex.ru"
      - "ok.ru"
      - "rutracker.org"
